/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_securitycode_libipfwjni_IpFw */

#ifndef _Included_ru_securitycode_libipfwjni_IpFw
#define _Included_ru_securitycode_libipfwjni_IpFw
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_securitycode_libipfwjni_IpFw
 * Method:    createIpFw
 * Signature: (Lru/securitycode/libipfwjni/IpFwSetting;)V
 */
JNIEXPORT void JNICALL Java_ru_securitycode_libipfwjni_IpFw_createIpFw
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ru_securitycode_libipfwjni_IpFw
 * Method:    startIpFw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_securitycode_libipfwjni_IpFw_startIpFw
  (JNIEnv *, jobject);

/*
 * Class:     ru_securitycode_libipfwjni_IpFw
 * Method:    stopIpFw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_securitycode_libipfwjni_IpFw_stopIpFw
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
